site_name: tamil-utils
repo_url: https://github.com/arulnidhii/tamil-utils
edit_uri: blob/main/docs/

theme:
  name: material
  features:
    - content.code.copy
    - navigation.top
    - search.highlight

nav:
  - Home: index.md
  - Usage: usage.md
  - API: api.md
  - Recipes: recipes.md
  - Collation: collation.md
  - Preprocess: preprocess.md
  - Hugging Face: hf.md
  - spaCy: spacy.md
  - Corpus: corpus.md
  - NER: ner.md